spring:
  cloud:
    azure:
      eventhubs:
        namespace: eh-bidbax-test
#        namespace: ${AZURE_EVENTHUBS_NAMESPACE}
        processor:
          checkpoint-store:
            account-name: sabidbaxtest82de5a
#            account-name: ${AZURE_STORAGE_CONTAINER_NAME}
            container-name: bidbaxtestcontainer
#            container-name: ${AZURE_STORAGE_ACCOUNT_NAME}
    stream:
      bindings:
        consume-in-0:
          destination: weather-guesses
#          destination: ${AZURE_EVENTHUB_NAME}
          group: weather-guessers
#          group: ${AZURE_EVENTHUB_CONSUMER_GROUP}
        supply-out-0:
          destination: weather-guesses # same as the above destination
#          destination: ${AZURE_EVENTHUB_NAME} # same as the above destination

      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      function:
        definition: consume;supply;
      poller:
        initial-delay: 0
        fixed-delay: 1000